name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get short commit SHA
        id: vars 
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "The SHORT_SHA name is ${GITHUB_ENV}"
        
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Use Environment Variable
        run: echo "The environment name is ${{ vars.DOCKER_HUB_USERNAME }} and ${{ secrets.DOCKER_HUB_TOKEN }}"
      # Runs a set of commands using the runners shell
      - name: checkout
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
